# Numpy 数组及其索引

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#产生数组" data-toc-modified-id="产生数组-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>产生数组</a></span></li><li><span><a href="#数组属性" data-toc-modified-id="数组属性-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>数组属性</a></span></li><li><span><a href="#使用fill方法设定初始值" data-toc-modified-id="使用fill方法设定初始值-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>使用fill方法设定初始值</a></span></li><li><span><a href="#索引与切片" data-toc-modified-id="索引与切片-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>索引与切片</a></span></li><li><span><a href="#多维数组及其属性" data-toc-modified-id="多维数组及其属性-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>多维数组及其属性</a></span></li><li><span><a href="#多维数组索引" data-toc-modified-id="多维数组索引-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>多维数组索引</a></span></li><li><span><a href="#多维数组切片" data-toc-modified-id="多维数组切片-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>多维数组切片</a></span></li><li><span><a href="#切片是引用" data-toc-modified-id="切片是引用-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>切片是引用</a></span></li><li><span><a href="#花式索引是复制" data-toc-modified-id="花式索引是复制-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>花式索引是复制</a></span><ul class="toc-item"><li><span><a href="#一维" data-toc-modified-id="一维-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>一维</a></span></li><li><span><a href="#二维" data-toc-modified-id="二维-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>二维</a></span></li><li><span><a href="#不完全索引" data-toc-modified-id="不完全索引-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>不完全索引</a></span></li><li><span><a href="#三维花式索引" data-toc-modified-id="三维花式索引-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>三维花式索引</a></span></li></ul></li><li><span><a href="#where语句" data-toc-modified-id="where语句-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>where语句</a></span><ul class="toc-item"><li><span><a href="#一维" data-toc-modified-id="一维-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>一维</a></span></li><li><span><a href="#多维数组" data-toc-modified-id="多维数组-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>多维数组</a></span></li></ul></li></ul></div>

In [1]:
from numpy import *

## 产生数组

In [2]:
lst = [0,1,2,3]
a = array(lst)
a

array([0, 1, 2, 3])

In [3]:
# 直接传入
a = array([0,1,2,3])
a

array([0, 1, 2, 3])

## 数组属性

In [4]:
type(a)

numpy.ndarray

In [5]:
# 32bit整数
a.dtype

dtype('int32')

In [6]:
# 查看每个元素所占的字节
a.itemsize

4

In [7]:
# 查看形状：1维数组，返回一个元祖
a.shape

(4,)

In [8]:
shape(a)

(4,)

In [9]:
lst = [1,2,3,4]
shape(lst)

(4,)

In [10]:
a.size

4

In [11]:
size(a)

4

In [12]:
# 查看所有元素所占空间
a.nbytes
# 但事实上，数组所占的存储空间要比这个数字大，
# 因为要用一个header来保存shape，dtype这样的信息。

16

In [13]:
# 查看数组维数
a.ndim

1

## 使用fill方法设定初始值

In [14]:
a.fill(-4.8)
a
# 数组中要求所有元素的 dtype 是一样的，
# 如果传入参数的类型与数组类型不一样，需要按照已有的类型进行转换

array([-4, -4, -4, -4])

帮助文档是这样的：
```
Docstring:
a.fill(value)

Fill the array with a scalar value.

Parameters
----------
value : scalar
    All elements of `a` will be assigned this value.

Examples
--------
>>> a = np.array([1, 2])
>>> a.fill(0)
>>> a
array([0, 0])
>>> a = np.empty(2)
>>> a.fill(1)
>>> a
array([ 1.,  1.])
Type:      builtin_function_or_method
```

## 索引与切片

In [17]:
a = array([0,1,2,3])
a[0]

0

In [18]:
a[0]=10
a

array([10,  1,  2,  3])

In [19]:
a[1:3]

array([1, 2])

In [20]:
a[1:-2]

array([1])

In [21]:
# 省略参数
a[::2] # 步长为2

array([10,  2])

In [22]:
a[-2:]

array([2, 3])

In [23]:
# 记录一辆汽车表盘上每天显示的里程数
od = array([21000,21180,21240,22100,22400])

In [26]:
# 计算每天旅程
dist = od[1:] - od[:-1]
dist

array([180,  60, 860, 300])

```c
int compute_sum(int *arr, int N)
{
   int sum = 0;
   int i;
   for(i = 0; i<N; ++i)
   {
       sum += arr[i];
   }
   return sum;
}
```

## 多维数组及其属性

In [27]:
a = array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [28]:
# 形状
a.shape # 二行四列

(2, 4)

In [29]:
# 大小
a.size

8

In [32]:
# 维数
a.ndim

2

## 多维数组索引

In [33]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [34]:
a[1,3]

13

In [35]:
a[1,3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [36]:
# 索引整行
a[1]

array([10, 11, 12, -1])

## 多维数组切片

In [37]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [38]:
# 第一行的第4和第5个元素
a[0,3:5]

array([3, 4])

In [39]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [40]:
# 第三列
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

** 每一维都支持切片操作 `[lower:upper:step]`**

In [41]:
# 取出第3，5行的元素
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

## 切片是引用
**切片在内存中使用的是引用机制**

In [42]:
a = array([0,1,2,3,4])
b = a[2:4]
b

array([2, 3])

**引用机制意味着，Python并没有为 b 分配新的空间来存储它的值，而是让 b 指向了 a 所分配的内存空间，因此，改变 b 会改变 a 的值：**

In [43]:
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

In [44]:
# 列表中不存在
a = [1,2,3,4,5]
b = a[2:3]
b[0] = 13234
a

[1, 2, 3, 4, 5]

* 好处在于，对于很大的数组，不用大量复制多余的值，节约了空间
* 缺点在于，可能出现改变一个值改变另一个值的情况
* 解决方法是使用copy()方法产生一个复制，这个复制会申请新的内存

In [45]:
a = array([0,1,2,3,4])
b = a[2:4].copy()
# b = a.copy()属于浅拷贝，相当于复制一份，
# 原来的改变不影响复制后的，理解为独立的import copy
# b = copy.copy(a)是真正的深拷贝，b变a也变
b[0] = 10
a

array([0, 1, 2, 3, 4])

## 花式索引是复制

实现任意位置的操作，需要使用花式索引 `fancy slicing`

### 一维

In [46]:
# 与 range 函数类似，我们可以使用 arange 函数来产生等差数组
a = arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [47]:
indices = [1,2,-3]
y = a[indices]
y

array([10, 20, 50])

In [48]:
# 必须指定类型
mask = array([0,1,1,0,0,1,0,0],
             dtype=bool)

In [49]:
a[mask]

array([10, 20, 50])

In [50]:
# 用布尔表达式生成 mask，选出了所有大于0.5的值
from numpy.random import rand

In [53]:
rand??

![](https://raw.githubusercontent.com/ds19991999/githubimg/master/picgo/20180717231443.png)

In [52]:
a = rand(10)
a

array([0.30617538, 0.79258556, 0.64042199, 0.27588502, 0.96697624,
       0.21462333, 0.5933877 , 0.71378498, 0.71721819, 0.38522305])

In [54]:
# mask 必须是布尔数组,列表就不必
# 这个返回的就已经是bool类型，所以不用指定类型
mask = a > 0.5
a[mask]

array([0.79258556, 0.64042199, 0.96697624, 0.5933877 , 0.71378498,
       0.71721819])

### 二维

In [55]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [56]:
# 对于二维花式索引，我们需要给定 row 和 col 的值：
# 返回的是一条次对角线上的5个值。
a[(0,1,2,3,4), (1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [57]:
# 返回的是最后三行的第1，3，5列。
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [58]:
# 也可以使用mask进行索引
mask = array([1,0,1,0,0,1],
            dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

### 不完全索引

In [59]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [60]:
# 只给定行索引的时候，返回整行
y = a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [62]:
# 这时候也可以使用花式索引取出第2，3，5行
condition = array([0,1,1,0,1,0],
                 dtype=bool)
a[condition]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

### 三维花式索引

In [63]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [64]:
# 对于多维数组索引，可以按照索引参数的顺序
# 从数组最外层向最内层进行查看理解
y = a[:,:,[2, -1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

## where语句

In [65]:
where(array)
# where 的返回值是一个元组

(array([0]),)

In [66]:
# 返回所有非零元素的索引。
where(a)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0, 0, 1, 1, 1,
        1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3,
        3, 3, 3, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2,
        3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0,
        1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

### 一维

In [67]:
a = array([0, 12, 5, 20])
a > 10

array([False,  True, False,  True])

In [68]:
# 返回满足条件的索引
where(a > 10)

(array([1, 3]),)

In [69]:
indices = where(a > 10)
indices = indices[0]
indices

array([1, 3])

In [70]:
# 索引直接写在后面
indices = where(a>10)[0]
indices

array([1, 3])

### 多维数组

In [71]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = where(a > 10)
loc # 返回二维元组，每一维代表这一维的索引

(array([0, 0, 1, 1]), array([1, 3, 2, 3]))

In [72]:
# 直接索引满足条件的元素
a[loc]

array([12, 20, 11, 15])

In [73]:
a[where(a>10)]

array([12, 20, 11, 15])

In [75]:
row,col = where(a>10)
a[row,col]

array([12, 20, 11, 15])

In [76]:
a = arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))