# 数组类型

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#复数数组" data-toc-modified-id="复数数组-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>复数数组</a></span></li><li><span><a href="#指定数组类型" data-toc-modified-id="指定数组类型-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>指定数组类型</a></span></li><li><span><a href="#Numpy类型" data-toc-modified-id="Numpy类型-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Numpy类型</a></span></li><li><span><a href="#类型转换" data-toc-modified-id="类型转换-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>类型转换</a></span><ul class="toc-item"><li><span><a href="#asarray函数" data-toc-modified-id="asarray函数-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>asarray函数</a></span></li><li><span><a href="#astype方法" data-toc-modified-id="astype方法-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>astype方法</a></span></li><li><span><a href="#view方法" data-toc-modified-id="view方法-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>view方法</a></span></li></ul></li></ul></div>

In [2]:
from numpy import *

## 复数数组

In [3]:
# 产生一个复数数组
a = array([1+1j,2,3,4])
a.dtype

dtype('complex128')

In [4]:
a.real

array([1., 2., 3., 4.])

In [5]:
a.imag

array([1., 0., 0., 0.])

In [6]:
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [7]:
# 共轭复数
a.conj()

array([1.-1.j, 2.-0.j, 3.-0.j, 4.-0.j])

事实上，这些属性方法可以用在浮点数或者整数数组上

但这里，虚部是只读的，并不能修改它的值

In [8]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [9]:
a.real

array([0., 1., 2., 3.])

In [10]:
a.imag

array([0., 0., 0., 0.])

In [11]:
a.conj()

array([0., 1., 2., 3.])

In [12]:
# 报错
a.imag = [1,2,3,4]

TypeError: array does not have imaginary part to set

## 指定数组类型

In [14]:
# 根据传入的参数自动判断类型
a = array([0,1.0,2,3])
a.dtype

dtype('float64')

In [15]:
# 查看所用字节
a.nbytes

32

In [16]:
# 直接指定数据类型
a = array([1,1.0,2,3],
         dtype=float32)
a.dtype

dtype('float32')

In [17]:
a.nbytes

16

In [22]:
# 无符号整数
# uint8 只使用一个字节，表示 0 到 255 的整数
a = array([0,1,2,3],
         dtype=uint8)
a.dtype

dtype('uint8')

In [23]:
# 从二进制中读取
# 先写入二进制数据
a = array([102,111,212],
         dtype=uint8)
a.tofile('foo.dat')

In [27]:
# 从数据中读取，需要指定数据类型，否则报错
b = frombuffer('foo',dtype=uint8)
b

array([102, 111, 111], dtype=uint8)

In [29]:
a.tofile??

In [30]:
import os
os.remove('foo.dat')

In [31]:
#  ord 函数来查看字符的ASCⅡ码值
ord('f')

102

In [32]:
ord('F')

70

In [33]:
ord??

## Numpy类型

基本类型|可用的Numpy类型|备注
-----|----------------------------------------|----------
布尔型|`int8,int16,int32,int64,int128,int`|`int` 跟C语言中的`long` 一样大
整型|`uint8, uint16, uint32, uint64, uint128, uint`|`uint` 跟C语言中的 `unsigned long` 一样大
无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`|`uint` 跟C语言中的 `unsigned long` 一样大
浮点数|float16, float32, float64, float, longfloat|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
复数|`complex64, complex128, complex, longcomplex`|默认为 `complex128` ，即实部虚部都为双精度
字符串|`string, unicode`|可以使用 `dtype=S4` 表示一个4字节字符串的数组
对象|`object`|数组中可以使用任意值
Records|`void`|
时间|`datetime64, timedelta64`|

In [34]:
dtype??

In [35]:
# 任意类型的数组：
a = array([1,1.2,'hello', [10,20,30]], 
          dtype=object)

In [36]:
a*2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

## 类型转换

In [37]:
# 转换数组的类型：
a = array([1.5,-3],
         dtype = float32)
a

array([ 1.5, -3. ], dtype=float32)

### asarray函数

In [39]:
asarray??

In [40]:
asarray(a, dtype=float64)

array([ 1.5, -3. ])

In [41]:
asarray(a, dtype=uint8)

array([  1, 253], dtype=uint8)

In [42]:
# asarray 不会修改原来数组的值：
a

array([ 1.5, -3. ], dtype=float32)

In [44]:
b = asarray(a, dtype=float32)

In [45]:
# 当类型相同的时候，asarray 并不会产生新的对象，而是使用同一个引用
b is a

True

In [46]:
# 保证我们的输入值是数组
asarray([1,2,3,4])

array([1, 2, 3, 4])

### astype方法

In [47]:
a

array([ 1.5, -3. ], dtype=float32)

In [48]:
# astype 方法返回一个新数组：
a.astype(float64)

array([ 1.5, -3. ])

In [50]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

In [51]:
# astype也不会改变原来数组的值：
a

array([ 1.5, -3. ], dtype=float32)

In [52]:
# astype 总是返回原来数组的一份复制，即使转换的类型是相同的：
b = a.astype(float32)
print a
print b

[ 1.5 -3. ]
[ 1.5 -3. ]


In [53]:
a is b

False

### view方法

In [54]:
a = array((1,2,3,4),dtype=int32)
a

array([1, 2, 3, 4])

In [55]:
# view 会将 a 在内存中的表示看成是 uint8 进行解析：
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [56]:
# 修改 a 会修改 b 的值，因为共用一块内存：
a[0] = 2**30
a

array([1073741824,          2,          3,          4])

In [57]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)