# 数组方法

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#求和" data-toc-modified-id="求和-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>求和</a></span></li><li><span><a href="#求积" data-toc-modified-id="求积-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>求积</a></span></li><li><span><a href="#求最大值最小值" data-toc-modified-id="求最大值最小值-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>求最大值最小值</a></span></li><li><span><a href="#最大最小值的位置" data-toc-modified-id="最大最小值的位置-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>最大最小值的位置</a></span></li><li><span><a href="#均值" data-toc-modified-id="均值-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>均值</a></span></li><li><span><a href="#标准差方差" data-toc-modified-id="标准差方差-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>标准差方差</a></span></li><li><span><a href="#clip方法" data-toc-modified-id="clip方法-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>clip方法</a></span></li><li><span><a href="#ptp方法" data-toc-modified-id="ptp方法-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>ptp方法</a></span></li><li><span><a href="#round方法" data-toc-modified-id="round方法-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>round方法</a></span></li></ul></div>

In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


## 求和

In [3]:
a = array([[1,2,3],
          [4,5,6]])

In [4]:
sum(a)

21

In [5]:
# 指定一维求和
sum(a,axis=0)

array([5, 7, 9])

In [6]:
# 指定二维求和
sum(a,axis=1)

array([ 6, 15])

In [7]:
# 指定最后一维求和
sum(a,axis=-1)

array([ 6, 15])

In [8]:
a.sum()

21

In [9]:
a.sum(axis=0)

array([5, 7, 9])

In [10]:
a.sum(axis=1)

array([ 6, 15])

In [11]:
a.sum(axis=-1)

array([ 6, 15])

## 求积

In [12]:
# 求所有元素乘积
a.prod()

720

In [13]:
prod(a,axis=1)

array([  6, 120])

## 求最大值最小值

In [14]:
from numpy.random import rand
a = rand(3,4) # 三行四列
%precision 3 # 三位小数
a

array([[0.304, 0.508, 0.171, 0.723],
       [0.822, 0.596, 0.441, 0.556],
       [0.235, 0.772, 0.269, 0.682]])

In [15]:
a.min()

0.1712786071747544

In [16]:
# 沿着一维最小
a.min(axis=0)

array([0.235, 0.508, 0.171, 0.556])

In [17]:
a.max()

0.8223151436894808

In [18]:
a.max(axis=-1)

array([0.723, 0.822, 0.772])

## 最大最小值的位置

In [19]:
# 使用 argmin, argmax 方法：
a.argmin()

2

In [20]:
a.argmax(axis=1)

array([3, 0, 1])

## 均值

In [21]:
# 可以使用 mean 方法
a = array([[1,2,3],[4,5,6]])
a.mean()

3.5

In [22]:
a.mean(axis=-1)

array([2., 5.])

In [23]:
# 也可以使用 mean 函数：
mean(a)

3.5

In [24]:
# 还可以使用 average 函数：
average(a,axis=0)

array([2.5, 3.5, 4.5])

In [26]:
# average 函数还支持加权平均：
average(a, axis = 0, weights=[1,2])

array([3., 4., 5.])

## 标准差方差

In [27]:
# 用 std 方法计算标准差：
a.std(axis=1)

array([0.816, 0.816])

In [28]:
# 用 var 方法计算方差：
a.var(axis=1)

array([0.667, 0.667])

In [29]:
var(a, axis=1)

array([0.667, 0.667])

In [32]:
std(a, axis=1)

array([0.816, 0.816])

## clip方法

In [33]:
# 将数值限制在某个范围：
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# 小于3的变成3，大于5的变成5
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## ptp方法

In [35]:
# 计算最大值和最小值之差：
a.ptp(axis=1)

array([2, 2])

In [36]:
a.ptp()

5

## round方法

In [37]:
# 近似，默认到整数：
# 5的近似以接近偶数为原则，尽量使近似后为偶数
a = array([1.35, 2.5, 1.5])

In [38]:
a.round()

array([1., 2., 2.])

In [39]:
# 近似到一位小数：
# 和precision魔法方法相似
a.round(decimals=1)

array([1.4, 2.5, 1.5])