# 数组排序

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#sort函数" data-toc-modified-id="sort函数-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>sort函数</a></span></li><li><span><a href="#argsort函数" data-toc-modified-id="argsort函数-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>argsort函数</a></span></li><li><span><a href="#sort和argsort方法" data-toc-modified-id="sort和argsort方法-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>sort和argsort方法</a></span></li><li><span><a href="#二维数组排序" data-toc-modified-id="二维数组排序-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>二维数组排序</a></span></li><li><span><a href="#searchsorted-函数" data-toc-modified-id="searchsorted-函数-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>searchsorted 函数</a></span></li></ul></div>

In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


## sort函数

In [2]:
# sort 返回的结果是从小到大排列的。
names = array(['bob','sue','jan','ad'])
weights = array([20.8,93.2,53.4,61.8])

sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [3]:
sort(names)

array(['ad', 'bob', 'jan', 'sue'], dtype='|S3')

## argsort函数

In [4]:
# argsort 返回从小到大的排列在数组中的索引位置：
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1])

In [6]:
# 可以用它来进行索引
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [8]:
names[argsort(names)]

array(['ad', 'bob', 'jan', 'sue'], dtype='|S3')

In [10]:
# 使用函数并不会改变原来数组的值：
weights

array([20.8, 93.2, 53.4, 61.8])

## sort和argsort方法

In [11]:
# 数组也支持方法操作：
data = array([20.8,93.2,53.4,61.8])
data.argsort() # argsort方法和argsort函数没区别

array([0, 2, 3, 1])

In [13]:
# 但是 sort方法会改变数组的值：
data.sort()
data

array([20.8, 53.4, 61.8, 93.2])

## 二维数组排序

In [14]:
# 对于多维数组，sort方法默认沿着最后一维开始排序：
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [15]:
# 对于二维数组，默认相当于对每一行进行排序：
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [16]:
# 改变轴，对每一列进行排序
sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

## searchsorted 函数

`searchsorted(sorted_array, values)`,searchsorted 接受两个参数，其中，第一个必需是已排序的数组。

In [17]:
sorted_array = linspace(0,1,5)# 范围0-1的5个数字，等间距
values = array([.1,.8,.3,.12,.5,.25])
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1])

searchsorted 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 0.1 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 1 处，故第一个返回值为 1

In [21]:
from numpy.random import rand
data = rand(100)
data.sort()

In [23]:
bounds = .4, .6
bounds # 这个是默认返回元组
# 之后的searchsorted函数将他当作数的范围

(0.4, 0.6)

In [24]:
low_idx, high_idx = searchsorted(data, bounds)

In [25]:
data[low_idx:high_idx]

array([0.40701631, 0.42667755, 0.43413705, 0.43780924, 0.43908061,
       0.45019972, 0.45446506, 0.46980766, 0.47690135, 0.49957373,
       0.50542106, 0.50843742, 0.53632764, 0.56316344, 0.56537545,
       0.56549469, 0.57918408, 0.58600115, 0.59611363])