# 数组形状

In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


## 修改数组的形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2,3

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
# 对应的方法是 reshape ，但它不会修改原来数组的值，而是返回一个新的数组：
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
# shape 和 reshape 方法不能改变数组中元素的总数，否则会报错：
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## 使用newaxis增加数组维数

In [8]:
a = arange(3)
shape(a)

(3,)

In [9]:
y = a[newaxis,:]
shape(y)

(1, 3)

In [10]:
a

array([0, 1, 2])

In [11]:
y

array([[0, 1, 2]])

In [12]:
# 根据插入位置的不同，可以返回不同形状的数组：
y = a[:, newaxis]
shape(y)

(3, 1)

In [13]:
y

array([[0],
       [1],
       [2]])

In [14]:
# 插入多个新维度：
y = a[newaxis, newaxis, :]
shape(y)

(1, 1, 3)

## squeeze 方法去除多余的轴

In [15]:
a = arange(6)
a.shape = (2,1,3)

In [16]:
# squeeze 返回一个将所有长度为1的维度去除的新数组。
b = a.squeeze()
b.shape

(2, 3)

## 数组转置

In [17]:
# 使用 transpose 返回数组的转置，本质上是将所有维度反过来：
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [18]:
# 对于二维数组，这相当于交换行和列：
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [19]:
# 或者使用缩写属性：
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

* 对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置
* 转置可以作用于多维数组

In [20]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [21]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [22]:
b = a.T
b.shape

(5, 4, 3)

* 所以转置只是交换了轴的位置
* 另一方面，转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。

In [23]:
b

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

In [24]:
a = arange(6)
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# 修改转置，a也会改变
b = a.T
b[0,1]=30

In [26]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

## 数组连接

`concatenate((a0,a1,...,aN), axis=0)`，这些数组要用 () 包括到一个元组中去，除了给定的轴外，这些数组其他轴的长度必须是一样的。

In [27]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print x.shape
print y.shape

(2, 3)
(2, 3)


In [28]:
# 默认沿着第一维进行连接：
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [29]:
z.shape

(4, 3)

In [30]:
# 沿着第二维进行连接：
z = concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [31]:
z.shape

(2, 6)

In [32]:
# x 和 y 的形状是一样,将它们连接成三维的数组
z = array((x,y))
z.shape

(2, 2, 3)

In [33]:
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

事实上，Numpy提供了分别对应这三种情况的函数：

* vstack
* hstack
* dstack

In [34]:
vstack((x,y)).shape

(4, 3)

In [35]:
hstack((x,y)).shape

(2, 6)

In [36]:
dstack((x,y)).shape

(2, 3, 2)

## Flatten数组

In [37]:
# flatten 方法的作用是将多维数组转化为1维数组：
# 返回的是数组的复制，因此，改变 b 并不会影响 a 的值：
a = array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [38]:
b[0] = 10
print b
print a

[10  1  2  3]
[[0 1]
 [2 3]]


## flat属性

In [39]:
a

array([[0, 1],
       [2, 3]])

In [48]:
# a.flat 相当于返回了所有元组组成的一个迭代器：
a.flat

In [57]:
b = a.flat
b[:]

array([0, 1, 2, 3])

In [58]:
b[1]

1

In [59]:
# 此时修改b会影响a
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [60]:
a.flat[:]

array([10,  1,  2,  3])

## ravel 方法

In [61]:
# 除此之外，还可以使用 ravel 方法，ravel 使用高效的表示方式：
a = array([[0,1],
          [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [62]:
# 修改b会改变a
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [63]:
# 另一种情况
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [64]:
b[0] = 10
aa

array([[0, 2],
       [1, 3]])

In [65]:
a

array([[0, 1],
       [2, 3]])

修改 b 并不会改变 aa 的值，原因是我们用来 ravel 的对象 aa 本身是 a 的一个view。

## atleast_xd 函数

In [66]:
# 保证数组至少有 x 维：
x = 1
atleast_1d(x)

array([1])

In [67]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [68]:
b

array([[1, 2, 3]])

In [69]:
c = atleast_3d(b)
c.shape

(1, 3, 1)

In [70]:
c

array([[[1],
        [2],
        [3]]])

在**Scipy**库中，这些函数被用来保证输入满足一定的条件：

用法|Scipy中出现的次数
----|----
`value.flaten()、value.flat、value.ravel()`| ~2000次
`atleast_1d(value)、atleast_2d(value)`|~700次
`asarray(value)`|~4000次