# 矩阵

In [2]:
# 使用 mat 方法将 2 维数组转化为矩阵：
import numpy as np
a = np.array([[1,2,4],
             [2,5,3],
             [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [3]:
# 使用 Matlab 的语法传入一个字符串来生成矩阵
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [4]:
# 利用分块构造新的矩阵
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [6]:
# 矩阵和向量的乘法
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [9]:
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [10]:
x

array([[1],
       [2],
       [3]])

In [11]:
A*x

matrix([[17],
        [21],
        [50]])

In [12]:
# A.I表示A矩阵的逆矩阵
print A*A.I

[[1.00000000e+00 5.55111512e-17 1.38777878e-17]
 [0.00000000e+00 1.00000000e+00 6.93889390e-17]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [13]:
# 矩阵指数表示矩阵连乘：
A**4

matrix([[ 6497,  9580,  9836],
        [ 7138, 10561, 10818],
        [18434, 27220, 27945]])

In [14]:
A.I

matrix([[-0.42857143, -0.28571429,  0.28571429],
        [-0.06122449,  0.3877551 , -0.10204082],
        [ 0.3877551 , -0.12244898, -0.02040816]])

In [15]:
A.I*A

matrix([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [2.77555756e-17, 8.32667268e-17, 1.00000000e+00]])

设A是数域上的一个n阶方阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E。 则我们称B是A的逆矩阵，而A则被称为可逆矩阵