# 一般函数

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#三角函数" data-toc-modified-id="三角函数-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>三角函数</a></span></li><li><span><a href="#向量操作" data-toc-modified-id="向量操作-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>向量操作</a></span></li><li><span><a href="#其他操作" data-toc-modified-id="其他操作-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>其他操作</a></span></li><li><span><a href="#类型处理" data-toc-modified-id="类型处理-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>类型处理</a></span></li><li><span><a href="#修改形状" data-toc-modified-id="修改形状-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>修改形状</a></span></li><li><span><a href="#其他有用函数" data-toc-modified-id="其他有用函数-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>其他有用函数</a></span></li></ul></div>

In [1]:
import numpy as np

## 三角函数

```
sin(x)
cos(x)
tan(x)
sinh(x)
conh(x)
tanh(x)
arccos(x)
arctan(x)
arcsin(x)
arccosh(x)
arctanh(x)
arcsinh(x)
arctan2(x,y)
```

`arctan2(x,y) 返回 arctan(x/y) `

## 向量操作

```
dot(x,y)
inner(x,y)
cross(x,y)
vdot(x,y)
outer(x,y)
kron(x,y)
tensordot(x,y[,axis])
```

## 其他操作

```
exp(x)
log(x)
log10(x)
sqrt(x)
absolute(x)
conjugate(x)
negative(x)
ceil(x)
floor(x)
fabs(x)
hypot(x)
fmod(x)
maximum(x,y)
minimum(x,y)

```
hypot 返回对应点 (x,y) 到原点的距离

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

## 类型处理

```
iscomplexobj
iscomplex
isrealobj
isreal
imag
real
real_if_close
isscalar
isneginf
isposinf
isinf
isfinite
isnan
nan_to_num
common_type
typename
```

In [3]:
# 正无穷
np.inf

inf

In [4]:
# 负无穷
-np.inf

-inf

In [5]:
# 非法值
np.nan

nan

In [6]:
# 检查是否为无穷
np.isinf(1.0)

False

In [7]:
np.isinf(-np.inf)

True

In [8]:
# 非法值
# 返回一个非法值
np.array([0])/0.0

d:\python\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in divide
  


array([nan])

In [9]:
# 只有0/0会得到nan
a = np.arange(5.0)
b = a / 0.0
b

d:\python\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in divide
  This is separate from the ipykernel package so we can avoid doing imports until
d:\python\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan, inf, inf, inf, inf])

In [11]:
# nan与任何数进行比较都是Flase
b == np.nan

False

In [12]:
np.isnan(b)

True

## 修改形状

```
atleast_1d
atleast_2d
atleast_3d
expand_dims
apply_over_axes
apply_along_axis
hstack
vstack
dstack
column_stack
hsplit
vsplit
dsplit
split
squeeze
```

## 其他有用函数

```
fix
mod
amax
amin
ptp
sum
cumsum
prod
cumprod
diff
angle

unwrap
sort_complex
trim_zeros
fliplr
flipud
rot90
diag
eye
select
extract
insert

roots
poly
any
all
disp
unique
nansum
nanmax
nanargmax
nanargmin
nanmin

```

nan 开头的函数会进行相应的操作，但是忽略 nan 值。