# 记录数组

In [1]:
# 记录数组（record array）与结构数组类似：
import numpy as np

In [2]:
# 定义质点类型
my_dtype = np.dtype([('mass','float'),
                    ('velocity','float')])

In [3]:
# 生成记录数组要使用 numpy.rec 里的 fromrecords 方法：
from numpy import rec
particals_rec = rec.fromrecords([(1,1),(1,2),(2,1),(3,1)],
                                dtype = my_dtype)

In [4]:
particals_rec

rec.array([(1., 1.), (1., 2.), (2., 1.), (3., 1.)],
          dtype=[('mass', '<f8'), ('velocity', '<f8')])

In [5]:
# 同样可以通过属性获得域
particals_rec.mass

array([1., 1., 2., 3.])

In [6]:
particals_rec.velocity

array([1., 2., 1., 1.])

In [7]:
particals_rec['mass']

array([1., 1., 2., 3.])

**不过，记录数组的运行效率要比结构化数组要慢一些。**

In [8]:
# 也可以通过将一个结构化数组看成记录数组：
particals = np.array([(1,1), (1,2), (2,1), (1,3)],
                     dtype = my_dtype)

In [9]:
# 使用view方法看成recarray
particals_rec = particals.view(np.recarray)
particals_rec.mass

array([1., 1., 2., 1.])

In [10]:
# 对于自定义的类型，可以通过它的 names 属性查看它有哪些域：
particals.dtype.names

('mass', 'velocity')

In [11]:
particals[1]

(1., 2.)

In [12]:
particals['mass']

array([1., 1., 2., 1.])